#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/ai-lab/comfyui.env"
if [[ ! -r "$CONFIG_FILE" ]]; then
  echo "Missing ComfyUI config: $CONFIG_FILE" >&2
  exit 1
fi

# This file is generated by setup.sh and is writable only by the current user.
# shellcheck source=/dev/null
source "$CONFIG_FILE"

cd "$COMFYUI_REPO_DIR"
exec "$COMFYUI_VENV/bin/python" main.py \
  --listen "$COMFYUI_LISTEN_ADDRESS" \
  --port "${COMFYUI_PORT:-8188}" \
  --base-directory "$COMFYUI_DATA_DIR" \
  --models-directory "$COMFYUI_MODELS_DIR" \
  --output-directory "$COMFYUI_OUTPUT_DIR" \
  --disable-auto-launch
